### ISSUE TITLE
Regarding running code

### ISSUE THREAD

**Issue by tejaswi-gayathri** [jpuigcerver/jsp-ga#1]
Please let me know where is the file named "jsp-instance.txt" which is used to run the python file, and what are its contents
Also, what are the files in folders named L and S?

**Comment by jpuigcerver** [comment]
All the instances are in the "instances" folder. 

"L" and "S" refer to (L)arge and (S)mall instances. You can read about the differences here: https://github.com/jpuigcerver/jsp-ga/blob/master/instances/InstanceType

You can also create your own instance following the structure in https://github.com/jpuigcerver/jsp-ga/blob/master/instances/instanceStructure.
